[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
via_ir = false
optimizer_runs = 200
solc_version = "0.8.19"

gas_reports = ["*"]
fs_permissions = [{ access = "read", path = "./"}]

[fuzz]
runs = 1024
