[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
via_ir = true
optimizer_runs = 200
solc_version = "0.8.17"

gas_reports = ["*"]
fs_permissions = [{ access = "read", path = "./"}]

auto_detect_solc = true
